name: fruits_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  get_it: any
  go_router: ^16.3.0
  injectable: ^2.5.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  pinput: ^5.0.2
  retrofit: ^4.8.0
  shared_preferences: ^2.5.3
  svg_flutter: ^0.0.1
  intl: any
  dots_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.6
  injectable_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
fonts:
    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700